name: beta

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup Git Committer
        id: setup-git-committer
        uses: ./.github/actions/setup-git-committer
        with:
          openlegion-app-id: ${{ vars.OPENLEGION_APP_ID }}
          openlegion-app-secret: ${{ secrets.OPENLEGION_APP_SECRET }}

      - name: Install OpenLegion
        run: bun i -g openlegion-ai

      - name: Sync beta branch
        env:
          GH_TOKEN: ${{ steps.setup-git-committer.outputs.token }}
          OPENLEGION_API_KEY: ${{ secrets.OPENLEGION_API_KEY }}
        run: bun script/beta.ts
