import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["OPENLEGION_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("OPENLEGION_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENLEGION_AUTO_HEAP_SNAPSHOT: truthy("OPENLEGION_AUTO_HEAP_SNAPSHOT"),
  OPENLEGION_GIT_BASH_PATH: process.env["OPENLEGION_GIT_BASH_PATH"],
  OPENLEGION_CONFIG: process.env["OPENLEGION_CONFIG"],
  OPENLEGION_CONFIG_CONTENT: process.env["OPENLEGION_CONFIG_CONTENT"],
  OPENLEGION_DISABLE_AUTOUPDATE: truthy("OPENLEGION_DISABLE_AUTOUPDATE"),
  OPENLEGION_ALWAYS_NOTIFY_UPDATE: truthy("OPENLEGION_ALWAYS_NOTIFY_UPDATE"),
  OPENLEGION_DISABLE_PRUNE: truthy("OPENLEGION_DISABLE_PRUNE"),
  OPENLEGION_DISABLE_TERMINAL_TITLE: truthy("OPENLEGION_DISABLE_TERMINAL_TITLE"),
  OPENLEGION_SHOW_TTFD: truthy("OPENLEGION_SHOW_TTFD"),
  OPENLEGION_DISABLE_AUTOCOMPACT: truthy("OPENLEGION_DISABLE_AUTOCOMPACT"),
  OPENLEGION_DISABLE_MODELS_FETCH: truthy("OPENLEGION_DISABLE_MODELS_FETCH"),
  OPENLEGION_DISABLE_MOUSE: truthy("OPENLEGION_DISABLE_MOUSE"),
  OPENLEGION_FAKE_VCS: process.env["OPENLEGION_FAKE_VCS"],
  OPENLEGION_SERVER_PASSWORD: process.env["OPENLEGION_SERVER_PASSWORD"],
  OPENLEGION_SERVER_USERNAME: process.env["OPENLEGION_SERVER_USERNAME"],

  // Experimental
  OPENLEGION_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENLEGION_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENLEGION_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENLEGION_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENLEGION_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("OPENLEGION_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENLEGION_MODELS_URL: process.env["OPENLEGION_MODELS_URL"],
  OPENLEGION_MODELS_PATH: process.env["OPENLEGION_MODELS_PATH"],
  OPENLEGION_DB: process.env["OPENLEGION_DB"],

  OPENLEGION_WORKSPACE_ID: process.env["OPENLEGION_WORKSPACE_ID"],
  OPENLEGION_EXPERIMENTAL_WORKSPACES: enabledByExperimental("OPENLEGION_EXPERIMENTAL_WORKSPACES"),
  OPENLEGION_EXPERIMENTAL_SESSION_SWITCHER: enabledByExperimental("OPENLEGION_EXPERIMENTAL_SESSION_SWITCHER"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OPENLEGION_DISABLE_PROJECT_CONFIG() {
    return truthy("OPENLEGION_DISABLE_PROJECT_CONFIG")
  },
  get OPENLEGION_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("OPENLEGION_EXPERIMENTAL_REFERENCES")
  },
  get OPENLEGION_TUI_CONFIG() {
    return process.env["OPENLEGION_TUI_CONFIG"]
  },
  get OPENLEGION_CONFIG_DIR() {
    return process.env["OPENLEGION_CONFIG_DIR"]
  },
  get OPENLEGION_PURE() {
    return truthy("OPENLEGION_PURE")
  },
  get OPENLEGION_PERMISSION() {
    return process.env["OPENLEGION_PERMISSION"]
  },
  get OPENLEGION_PLUGIN_META_FILE() {
    return process.env["OPENLEGION_PLUGIN_META_FILE"]
  },
  get OPENLEGION_CLIENT() {
    return process.env["OPENLEGION_CLIENT"] ?? "cli"
  },
}
